@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

class Command {
    +execute(): CommandResult
}
class AddCommand {
    +details: String
    +execute(FoodList: foodList): CommandResult
    +splitDetails(String: details) : String[]
}
class CommandResult {
    +feedbackToUser:String
    +printResult(): void
}

Command <|-- AddCommand
CommandResult <-- AddCommand
CommandResult <-- Command

@enduml