@startuml
'https://plantuml.com/sequence-diagram

Duke -> Parser: parse(fullCommand)
activate Parser

create ExitCommand
ExitCommand <- Parser : ExitCommand(arguments)
activate ExitCommand
ExitCommand --> Parser
deactivate ExitCommand
deactivate Parser

Duke -> ExitCommand : execute(foodList)
activate ExitCommand



create CommandResult
ExitCommand -> CommandResult : CommandResult(printToUser)
activate CommandResult
deactivate ExitCommand
destroy ExitCommand

Duke -> CommandResult: printResult()
CommandResult->System: out.println(feedbackToUser)

System --> CommandResult
CommandResult --> Duke
deactivate CommandResult
destroy CommandResult

Duke -> ExitCommand: isExit()
activate ExitCommand
ExitCommand --> Duke
deactivate ExitCommand
destroy ExitCommand

destroy Duke

@enduml