@startuml

Duke -> Parser: parse(command)
activate Parser

create FindCommand
FindCommand <- Parser : FindCommand(arguments)
activate FindCommand
FindCommand --> Parser
deactivate FindCommand
deactivate Parser

Duke -> FindCommand : execute(foodList)
activate FindCommand

create FoodList as Result
FindCommand -> Result: new FoodList();
activate Result
Result -> FindCommand
deactivate Result

loop for every foodItem
    opt hasTerm
        opt no flags
            FindCommand -> Result: addFood()
        end

        opt all flags satisfied
            FindCommand -> Result: addFood()
        end

        opt flag not satisfied
             FindCommand -> FindCommand: continue
        end
    end
end


create CommandResult
FindCommand -> CommandResult : CommandResult(FoodList)
activate CommandResult
deactivate FindCommand
destroy FindCommand

Duke -> CommandResult: printResult()
CommandResult->System: System.out.println(feedbackToUser)
deactivate CommandResult
destroy CommandResult

System --> Duke
@enduml