@startuml

":FoodSupplyTracker" -> ":Parser": parse(command)
activate ":Parser"

create ":FindCommand"
":FindCommand" <- ":Parser" : FindCommand(arguments)
activate ":FindCommand"
":FindCommand" --> ":Parser"
deactivate ":FindCommand"
deactivate ":Parser"

":FoodSupplyTracker" -> ":FindCommand" : execute(foodList)
activate ":FindCommand"

create ":FoodList" as Result
":FindCommand" -> Result: new FoodList();
activate Result
Result -> ":FindCommand"
deactivate Result

loop for every foodItem
    opt hasTerm
        alt flag not satisfied
             ":FindCommand" -> ":FindCommand": continue loop
        else all flags satisfied
            ":FindCommand" -> Result: addFood()
        end
    end
end


create ":CommandResult"
":FindCommand" -> ":CommandResult" : CommandResult(FoodList)
activate ":CommandResult"
deactivate ":FindCommand"
destroy ":FindCommand"

":FoodSupplyTracker" -> ":CommandResult": printResult()
":CommandResult"->System: System.out.println(feedbackToUser)
deactivate ":CommandResult"
destroy ":CommandResult"

System --> ":FoodSupplyTracker"
@enduml