@startuml
'https://plantuml.com/sequence-diagram



":Duke" -> ":Parser": parse(fullCommand)
activate ":Parser"

create ":HelpCommand" as hc
hc <- ":Parser" : ":HelpCommand"(arguments)
activate hc
hc --> ":Parser"
deactivate hc
deactivate ":Parser"



":Duke" -> hc : execute(foodList)
activate hc

alt filter size <= 1

else
loop all filters
hc -> hc : appendMessage(printToUser, filter)
activate hc
hc --> hc
deactivate hc
end
end

create ":CommandResult" as cr
hc -> cr : ":CommandResult"(printToUser)
activate cr
deactivate hc
destroy hc

":Duke" -> cr: printResult()
cr->System: out.println(feedbackToUser)


System --> cr
cr --> ":Duke"
deactivate cr
destroy cr

@enduml