@startuml
'https://plantuml.com/sequence-diagram

participant Duke
participant RemoveCommand
participant FoodList as foodList


Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml