@startuml
'https://plantuml.com/sequence-diagram

participant ":FoodSupplyTracker"
participant ":RemoveCommand"


":FoodSupplyTracker" -> ":RemoveCommand" : execute(arguments)
activate ":RemoveCommand"

":RemoveCommand" -> ":FoodList" : getFood(index)
activate ":FoodList"

":FoodList" -> ":FoodList" : getName()

":FoodList" --> ":RemoveCommand" : foodName

":RemoveCommand" --> ":FoodSupplyTracker" : new CommandResult()

@enduml